### ISSUE TITLE
Offline yeelight devices are not shown as offline

### ISSUE THREAD

**Issue by LasseRosenow** [mozilla-iot/yeelight-adapter#10]
I have a yeelight bulb and its always shown as online even if it has no power at all.

Its always like this:
![image](https://user-images.githubusercontent.com/10547444/79696694-9f666700-827e-11ea-97ef-6e1f65b58504.png)

If I click on it, its like this:
![image](https://user-images.githubusercontent.com/10547444/79696703-a9886580-827e-11ea-9b25-f536b472e0dc.png)

But if I click again nothing is happening anymore.... And after I reload the page its back to how it was before I clicked on it....

What I think it should look like is this:
![image](https://user-images.githubusercontent.com/10547444/79696754-e5232f80-827e-11ea-8fdc-b3292d5b46cd.png)
This image is from another device which I wrote myself with the Arduino framework and it gets half transparent when its offline.

**Comment by mrstegeman** [comment]
This should be fixed in v0.3.1.
