### ISSUE TITLE
Adding "Toggle" action

### ISSUE THREAD

**Issue by nikitaindik** [mozilla-iot/yeelight-adapter#11]
I would like to toggle my bulb when I push a wireless button. It seems like currently it's not possible - you have to choose either "On" or "Off".

<img width="1235" alt="Screenshot 2020-05-16 at 21 22 32" src="https://user-images.githubusercontent.com/15949146/82128434-7ec8f880-97bb-11ea-8082-142dfe8c665f.png">

Do you think it's a good idea to add a "Toggle" action to the device dropdown? I can try to implement this and open a PR if you are open to the idea.

**Comment by mrstegeman** [comment]
What I typically do is create 2 rules, as follows:

1. If light is on and button is pushed, turn light off.
2. If light is off and button is pushed, turn light on.

**Comment by nikitaindik** [comment]
@mrstegeman Yaay! It totally works! Didn't know you can combine it like this. Thanks!

Also, is there a way to start a color flow when some event occurs? For example flash the light a couple times when a message arrives.

**Comment by mrstegeman** [comment]
You could do this with a combination of "virtual" devices, e.g. via the Timer and Counter adapters.
1. If "event" occurs, turn light on, increment counter and start timer.
2. If timer is elapsed and counter == 1, turn light off, increment counter, and start timer.
3. If timer is elapsed and counter == 2, turn light on, increment counter, and start timer.
4. If timer is elapsed and counter == 3, turn light off and reset counter.

This is obviously a bit more complicated, but it should do the trick.

**Comment by nikitaindik** [comment]
@mrstegeman Thanks.
