### ISSUE TITLE
Changing bulb state via external app is not reflected in Gateway UI

### ISSUE THREAD

**Issue by nikitaindik** [mozilla-iot/yeelight-adapter#12]
When I use something other than Gateway UI to change bulb state, Gateway doesn't pick up these changes.

By changing bulb state I mean changing: on / off, brightness or color.

**Example**:
1. Turn the bulb ON using Gateway UI
2. Turn the bulb OFF using Google Home app on a smartphone
3. Check Gateway UI - bulb is shown an "ON"
4. Reload the page - still "ON"

I tried changing bulb state with:
 - Google Home app
 - Google Home Mini speaker
 - Yeelight Android app
 - Custom Node.js script that connects to the bulb

Using any of above to control the bulb doesn't work well with the Gateway. But, for example, if I change bulb state using Google Home app, Yeelight and other apps see the change.

Is this a bug with "yeelight-adapter" / "gateway" or there's something wrong with my configuration?

I am using "gateway" v0.12 and "yeelight-adapter" v0.3.1

**Comment by mrstegeman** [comment]
The devices should all be polled every 5 seconds. Are you never seeing updates, even if you wait 5-10 seconds?

**Comment by nikitaindik** [comment]
@mrstegeman Yes, waiting doesn't help. Also if I connect to the bulb via Node.js script, I can see that the bulb posts messages to all subscribed apps on state change. Is "yeelight-adapter" subscribed to these updates? Or it just polls the bulb every 5 secs or so? If it just polls, maybe there's an issue with polling.

**Comment by mrstegeman** [comment]
No, this adapter uses the [yeelight](https://yeelight.readthedocs.io/en/stable/) Python module, which doesn't provide anything like that.

What Node library are you using? This add-on could probably be rewritten in JS if the library is better (and stable).

**Comment by nikitaindik** [comment]
Oh, I don't use a library. I just use Node's native "net" module to send JSONs to bulb's IP/port as described in this doc: https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf

It looks like there are some Node libraries for this, but I've never used them and don't know if they are good and maintained :(

**Comment by mrstegeman** [comment]
[This one](https://www.npmjs.com/package/yeelight-node) looks to be the most maintained, but it seems like it also doesn't handle the NOTIFICATION messages.

Do you have any interest in writing a simple library to do discovery and control that we could use in this add-on, or maybe submitting a pull request that adds NOTIFICATION support to the yeelight-node library?

**Comment by nikitaindik** [comment]
Sure, I'm interested. But do you think adding support for "notification" messages to the current Python library is a bad idea?

**Comment by mrstegeman** [comment]
No, I'd also be happy with that, and that would save me work. 😄

**Comment by nikitaindik** [comment]
Checked the Python lib. Looks like maintainers were thinking about adding this feature, but they got stuck because of some implementation difficulties. So it's probably not our best bet.
https://gitlab.com/stavros/python-yeelight/-/issues/4

Also checked "yeelight-node". It seems usable. I was able to receive notifications with this snippet:

```javascript
const { Client } = require("yeelight-node");

const client = new Client();

client.bind(onDeviceDiscovered);

function onDeviceDiscovered(yeelight) {
  yeelight.client.connect(yeelight.port, yeelight.ip);

  yeelight.client.on("data", (data) => {
    const message = parseMessageString(data);

    if (!message.parseError && isNotificationMessage(message)) {
      console.log("Bulb state changed!", message);
    }
  });
}

function parseMessageString(data) {
  try {
    return JSON.parse(data);
  } catch (error) {
    return {
      parseError: "Message is not a valid JSON",
    };
  }
}

function isNotificationMessage(message) {
  const messageKeys = Object.keys(message);
  return messageKeys.includes("method") && messageKeys.includes("params");
}
```

What do you think?

**Comment by mrstegeman** [comment]
Thanks! That seems to be working well. Give v0.4.0 a shot and see how it does.
