### ISSUE TITLE
Some dependencies are not listed in package.json

### ISSUE THREAD

**Issue by nikitaindik** [mozilla-iot/yeelight-adapter#13]
I've noticed that some dependencies (like "gateway-addon" and "querystring") are not listed in package.json.
Also package-lock.json is in .gitignore.
Is there a specific reason for this?

**Comment by mrstegeman** [comment]
Any addition details? What’s missing?

**Comment by nikitaindik** [comment]
Sorry, I accidentally hit "Enter" and the issue got created before I had a chance to add description. Updated.

**Comment by nikitaindik** [comment]
That was quick, by the way :D

**Comment by mrstegeman** [comment]
querystring is built into Node. gateway-addon is provided by the gateway, as it has to be version-matched to the gateway itself.

**Comment by nikitaindik** [comment]
Didn't know that "querystring" is a Node built-in. Now I know :)
Asked about "gateway-addon" because I saw it listed in "zigbee-adapter" package.json.

Anyways, thanks for clarification. Closing.
